version: '3.3'

services:
  weather-frontend:
    container_name: weather-frontend
    build: .
    volumes:
      - .:/app
    ports:
      - "${FRONTEND_LOCAL_TCP_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:${DOCKER_BRIDGE_HOST_IP}"
    environment:
      VUE_APP_BUILD_COMMIT: "${BUILD_COMMIT}"
      VUE_APP_BUILD_DATE: "${BUILD_DATE}"
    #   VUE_APP_RSA_PUBLIC_KEY: | # This key is only used for local dev environment and thus committed to Git
    #     -----BEGIN PUBLIC KEY-----
    #     MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyPXQmiuJYdKp9c8EOr6q
    #     pwnRx20bhjn7Q7gxCYM2cMkD3ho3RuKxczxBN1DyU6jwsSRMQxOn91lTqcALgH26
    #     /KkghTRAyPky6ClWOnM381QuHADKAS8ryp5ubymFRmZip1TdF9VEm5migWmxs/mo
    #     JOjWFcfIWFnZcJYl42vG/ltqHAynnyu5XZ1IlxfPPPH+fUwdusNM0dYCEy2JxtfF
    #     7A3TgCOmNad5cjXQpcZY6F2aQk5UdECmPBf4RoGuGX+0GAuFRdWXl8OKPKNyIiX6
    #     TAicHrvkFMhAvOLfAvuSTtrpdd86eT9usg85uvvQbgpeXNsANEU3YpmZs4/Eft7c
    #     Je2cNrkRzU7XlbaBZ4eHAeOhbmKt07FhASkyBV0VKXcnpBtIANIAXPp10sMkJRg6
    #     ZBaTBU2leBwPgVgpUkMNcCK4T59rV6W76B7oZgeykwFv9h+DTDGZxuoIdUU+mman
    #     aBhIBFbYSWW6tZHC/X9LlE0Lz1QGQSynFpf0L77iXVcvhJtAtVkb8vl/ITExdiOg
    #     8ZYoEBR0O4sCK37tcmJgQrhbqMGGzaAEga02dNSs/gjqoboMrxfWxEqcwifeI7/h
    #     QeTBB/w5KRZePD3W035UF4JJho7xazORV2n1UD99OuGYZ71q4FXeZvtPfEkmGMNl
    #     OZkJgT8InOm1UEFAiDBgiMUCAwEAAQ==
    #     -----END PUBLIC KEY-----